### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by bszonye** [bszonye/bones#5]
The `bones` project is already claimed on PyPI.

Possible alternatives & notes:

- boxcars: dice-specific, long
- dembones: long
- dsix: overly specific
- dtwenty: overly specific, long
- oddly: elegant except for the "app.ly" naming fad
- oddball: long, cryptic
- otter: cryptic
- pippin: includes cards & dominoes
- snekeyes: twee

**Comment by posita** [comment]
Others?

* `dbones`
* `rollin`

FWIW, I like `oddly`.

**Comment by bszonye** [comment]
Yeah, `oddly` goes well with my module naming convention. I've been giving them verb names like `roll` for dice and `draw` for cards & bags, and `oddly.verb` works well. Speaking of which, I might also rename the `warhammer` module to just `hammer` to match. If that name doesn't work out, `pippin` is my second choice. Dice, cards, and dominoes all have pips, and there's even a vague allusion to Games Workshop's Middle-Earth game. Purely on vibes I prefer `oddly` though. Gonna sleep on it before making any final decisions. Thanks again for your input!

**Comment by bszonye** [comment]
I renamed the package to `oddly`, tested on test.pypyi.org, and now this:

> Client error '400 The name 'oddly' isn't allowed. See https://pypi.org/help/#project-name for more information.' for url 'https://upload.pypi.org/legacy/'
